### ISSUE TITLE
compile failure with the latest unbundled prometheus-cpp

### ISSUE THREAD

**Issue by asarubbo** [drachtio/drachtio-server#232]
Hello Dave,

while trying to unblundle stuff mentioned in #222 I noticed that it fails to compile with the latest prometheus-cpp (1.0.1):

```
src/stats-collector.cpp:20:55: error: ‘CKMSQuantiles’ is not a member of ‘prometheus::detail’
   20 |     using Quantiles = std::vector<prometheus::detail::CKMSQuantiles::Quantile>;
      |                                                       ^~~~~~~~~~~~~
src/stats-collector.cpp:20:78: error: template argument 1 is invalid
   20 |     using Quantiles = std::vector<prometheus::detail::CKMSQuantiles::Quantile>;
      |                                                                              ^
src/stats-collector.cpp:20:78: error: template argument 2 is invalid
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::buildCounter(const std::string&, const char*)’:
src/stats-collector.cpp:41:17: error: ‘BuildCounter’ was not declared in this scope; did you mean ‘buildCounter’?
   41 |       auto& m = BuildCounter()
      |                 ^~~~~~~~~~~~
      |                 buildCounter
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::counterIncrement(const std::string&, drachtio::StatsCollector::mapLabels_t&)’:
src/stats-collector.cpp:53:24: error: invalid use of incomplete type ‘class prometheus::Counter’
   53 |         it->second->Add(labels).Increment() ;
      |         ~~~~~~~~~~~~~~~^~~~~~~~
In file included from src/stats-collector.cpp:9:
/usr/include/prometheus/registry.h:16:7: note: forward declaration of ‘class prometheus::Counter’
   16 | class Counter;
      |       ^~~~~~~
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::counterIncrement(const std::string&, double, drachtio::StatsCollector::mapLabels_t&)’:
src/stats-collector.cpp:59:24: error: invalid use of incomplete type ‘class prometheus::Counter’
   59 |         it->second->Add(labels).Increment(val) ;
      |         ~~~~~~~~~~~~~~~^~~~~~~~
/usr/include/prometheus/registry.h:16:7: note: forward declaration of ‘class prometheus::Counter’
   16 | class Counter;
      |       ^~~~~~~
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::buildGauge(const std::string&, const char*)’:
src/stats-collector.cpp:64:17: error: ‘BuildGauge’ was not declared in this scope; did you mean ‘buildGauge’?
   64 |       auto& m = BuildGauge()
      |                 ^~~~~~~~~~
      |                 buildGauge
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::gaugeIncrement(const std::string&, drachtio::StatsCollector::mapLabels_t&)’:
src/stats-collector.cpp:76:24: error: invalid use of incomplete type ‘class prometheus::Gauge’
   76 |         it->second->Add(labels).Increment() ;
      |         ~~~~~~~~~~~~~~~^~~~~~~~
/usr/include/prometheus/registry.h:17:7: note: forward declaration of ‘class prometheus::Gauge’
   17 | class Gauge;
      |       ^~~~~
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::gaugeIncrement(const std::string&, double, drachtio::StatsCollector::mapLabels_t&)’:
src/stats-collector.cpp:83:24: error: invalid use of incomplete type ‘class prometheus::Gauge’
   83 |         it->second->Add(labels).Increment(val) ;
      |         ~~~~~~~~~~~~~~~^~~~~~~~
/usr/include/prometheus/registry.h:17:7: note: forward declaration of ‘class prometheus::Gauge’
   17 | class Gauge;
      |       ^~~~~
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::gaugeDecrement(const std::string&, drachtio::StatsCollector::mapLabels_t&)’:
src/stats-collector.cpp:90:24: error: invalid use of incomplete type ‘class prometheus::Gauge’
   90 |         it->second->Add(labels).Decrement() ;
      |         ~~~~~~~~~~~~~~~^~~~~~~~
/usr/include/prometheus/registry.h:17:7: note: forward declaration of ‘class prometheus::Gauge’
   17 | class Gauge;
      |       ^~~~~
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::gaugeDecrement(const std::string&, double, drachtio::StatsCollector::mapLabels_t&)’:
src/stats-collector.cpp:97:24: error: invalid use of incomplete type ‘class prometheus::Gauge’
   97 |         it->second->Add(labels).Decrement(val) ;
      |         ~~~~~~~~~~~~~~~^~~~~~~~
/usr/include/prometheus/registry.h:17:7: note: forward declaration of ‘class prometheus::Gauge’
   17 | class Gauge;
      |       ^~~~~
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::gaugeSet(const std::string&, double, drachtio::StatsCollector::mapLabels_t&)’:
src/stats-collector.cpp:104:24: error: invalid use of incomplete type ‘class prometheus::Gauge’
  104 |         it->second->Add(labels).Set(val) ;
      |         ~~~~~~~~~~~~~~~^~~~~~~~
/usr/include/prometheus/registry.h:17:7: note: forward declaration of ‘class prometheus::Gauge’
   17 | class Gauge;
      |       ^~~~~
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::gaugeSetToCurrentTime(const std::string&, drachtio::StatsCollector::mapLabels_t&)’:
src/stats-collector.cpp:111:24: error: invalid use of incomplete type ‘class prometheus::Gauge’
  111 |         it->second->Add(labels).SetToCurrentTime() ;
      |         ~~~~~~~~~~~~~~~^~~~~~~~
/usr/include/prometheus/registry.h:17:7: note: forward declaration of ‘class prometheus::Gauge’
   17 | class Gauge;
      |       ^~~~~
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::buildHistogram(const std::string&, const char*, const drachtio::StatsCollector::BucketBoundaries&)’:
src/stats-collector.cpp:116:17: error: ‘BuildHistogram’ was not declared in this scope; did you mean ‘buildHistogram’?
  116 |       auto& m = BuildHistogram()
      |                 ^~~~~~~~~~~~~~
      |                 buildHistogram
src/stats-collector.cpp: In member function ‘void drachtio::StatsCollector::PromImpl::histogramObserve(const std::string&, double, drachtio::StatsCollector::mapLabels_t&)’:
src/stats-collector.cpp:130:21: error: invalid use of incomplete type ‘class prometheus::Histogram’
  130 |         pFamily->Add(labels, spec.buckets).Observe(val);
      |         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/usr/include/prometheus/registry.h:18:7: note: forward declaration of ‘class prometheus::Histogram’
   18 | class Histogram;
      |       ^~~~~~~~~
In file included from /usr/include/prometheus/family.h:12,
                 from /usr/include/prometheus/registry.h:10:
/usr/include/prometheus/detail/future_std.h: In instantiation of ‘std::unique_ptr<_Tp> prometheus::detail::make_unique(Args&& ...) [with T = prometheus::Counter; Args = {}]’:
/usr/include/prometheus/family.h:113:46:   required from ‘T& prometheus::Family<T>::Add(const prometheus::Labels&, Args&& ...) [with Args = {}; T = prometheus::Counter; prometheus::Labels = std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >]’
src/stats-collector.cpp:53:24:   required from here
/usr/include/prometheus/detail/future_std.h:12:29: error: invalid use of incomplete type ‘class prometheus::Counter’
   12 |   return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/prometheus/registry.h:16:7: note: forward declaration of ‘class prometheus::Counter’
   16 | class Counter;
      |       ^~~~~~~
/usr/include/prometheus/detail/future_std.h: In instantiation of ‘std::unique_ptr<_Tp> prometheus::detail::make_unique(Args&& ...) [with T = prometheus::Gauge; Args = {}]’:
/usr/include/prometheus/family.h:113:46:   required from ‘T& prometheus::Family<T>::Add(const prometheus::Labels&, Args&& ...) [with Args = {}; T = prometheus::Gauge; prometheus::Labels = std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >]’
src/stats-collector.cpp:76:24:   required from here
/usr/include/prometheus/detail/future_std.h:12:29: error: invalid use of incomplete type ‘class prometheus::Gauge’
   12 |   return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/prometheus/registry.h:17:7: note: forward declaration of ‘class prometheus::Gauge’
   17 | class Gauge;
      |       ^~~~~
/usr/include/prometheus/detail/future_std.h: In instantiation of ‘std::unique_ptr<_Tp> prometheus::detail::make_unique(Args&& ...) [with T = prometheus::Histogram; Args = {const std::vector<double, std::allocator<double> >&}]’:
/usr/include/prometheus/family.h:113:46:   required from ‘T& prometheus::Family<T>::Add(const prometheus::Labels&, Args&& ...) [with Args = {const std::vector<double, std::allocator<double> >&}; T = prometheus::Histogram; prometheus::Labels = std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >]’
src/stats-collector.cpp:130:21:   required from here
/usr/include/prometheus/detail/future_std.h:12:29: error: invalid use of incomplete type ‘class prometheus::Histogram’
   12 |   return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/prometheus/registry.h:18:7: note: forward declaration of ‘class prometheus::Histogram’
   18 | class Histogram;
      |       ^~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/memory:76,
                 from /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:35,
                 from /usr/include/boost/smart_ptr/detail/shared_count.hpp:27,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:17,
                 from /usr/include/boost/log/core/core.hpp:19,
                 from /usr/include/boost/log/core.hpp:20,
                 from /usr/include/boost/log/common.hpp:22,
                 from src/drachtio.h:41,
                 from src/stats-collector.cpp:5:
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = prometheus::Counter]’:
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/unique_ptr.h:396:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = prometheus::Counter; _Dp = std::default_delete<prometheus::Counter>]’
/usr/include/prometheus/family.h:113:46:   required from ‘T& prometheus::Family<T>::Add(const prometheus::Labels&, Args&& ...) [with Args = {}; T = prometheus::Counter; prometheus::Labels = std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >]’
src/stats-collector.cpp:53:24:   required from here
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/unique_ptr.h:93:23: error: invalid application of ‘sizeof’ to incomplete type ‘prometheus::Counter’
   93 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = prometheus::Gauge]’:
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/unique_ptr.h:396:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = prometheus::Gauge; _Dp = std::default_delete<prometheus::Gauge>]’
/usr/include/prometheus/family.h:113:46:   required from ‘T& prometheus::Family<T>::Add(const prometheus::Labels&, Args&& ...) [with Args = {}; T = prometheus::Gauge; prometheus::Labels = std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >]’
src/stats-collector.cpp:76:24:   required from here
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/unique_ptr.h:93:23: error: invalid application of ‘sizeof’ to incomplete type ‘prometheus::Gauge’
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = prometheus::Histogram]’:
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/unique_ptr.h:396:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = prometheus::Histogram; _Dp = std::default_delete<prometheus::Histogram>]’
/usr/include/prometheus/family.h:113:46:   required from ‘T& prometheus::Family<T>::Add(const prometheus::Labels&, Args&& ...) [with Args = {const std::vector<double, std::allocator<double> >&}; T = prometheus::Histogram; prometheus::Labels = std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >]’
src/stats-collector.cpp:130:21:   required from here
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/unique_ptr.h:93:23: error: invalid application of ‘sizeof’ to incomplete type ‘prometheus::Histogram’
make[1]: *** [Makefile:784: src/drachtio-stats-collector.o] Error 1
```

**Comment by davehorton** [comment]
Yes, I have it tied to a specific tag that does compile.  Updating the prometheus dependency would be fine, I guess, but I am not sure it is a high priority for me right now
